"""Add ExitLog model

Revision ID: e297f1374a78
Revises: 5f4d254183d3
Create Date: 2025-11-16 18:56:35.317914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e297f1374a78'
down_revision = '5f4d254183d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('door_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['door_id'], ['door.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exit_log')
    # ### end Alembic commands ###
